use anyhow::Result;

use crate::app::{InstallConfig, LogEntry};
use crate::theme;

pub fn generate_config(config: &InstallConfig, db_password: &str) -> Result<Vec<LogEntry>> {
    let mut logs = Vec::new();

    let install_dir = &config.install_dir;

    let admin_password = if config.admin_password.is_empty() {
        let pass = generate_random_string(16);
        logs.push(LogEntry::info(format!(
            "Generated admin password: {} (save this!)",
            pass
        )));
        pass
    } else {
        config.admin_password.clone()
    };

    let encryption_key = if config.connector_encryption_key.is_empty() {
        generate_random_string(32)
    } else {
        config.connector_encryption_key.clone()
    };

    // Resolve APP_URL host: use db_host if non-loopback, otherwise auto-detect
    let app_host = if config.db_host != "localhost" && config.db_host != "127.0.0.1" {
        config.db_host.clone()
    } else {
        detect_local_ip()
    };

    // Build DATABASE_URL
    let database_url = format!(
        "postgresql://{}:{}@{}:{}/{}",
        config.db_user, db_password, config.db_host, config.db_port, config.db_name
    );

    // License values are embedded at compile time via GitHub Secrets
    let license_server_url = theme::LICENSE_SERVER_URL;
    let license_api_key = theme::LICENSE_API_KEY;
    let license_grace_period = theme::LICENSE_GRACE_PERIOD_DAYS;
    let license_public_key = theme::LICENSE_PUBLIC_KEY;

    // Generate .env file
    let env_content = format!(
        r#"# NQRust-InfraWatch Configuration
# Generated by infrawatch-installer v{version}

# Database
DATABASE_URL={database_url}

# Security
CONNECTOR_ENCRYPTION_KEY={encryption_key}

# Admin User
ADMIN_USERNAME={admin_username}
ADMIN_PASSWORD={admin_password}

# License (embedded at build time — do not modify)
LICENSE_SERVER_URL={license_server_url}
LICENSE_API_KEY={license_api_key}
LICENSE_GRACE_PERIOD_DAYS={license_grace_period}
LICENSE_PUBLIC_KEY="{license_public_key}"

# Server
PORT={port}
APP_URL=http://{app_host}:{port}
"#,
        version = theme::VERSION,
        database_url = database_url,
        encryption_key = encryption_key,
        admin_username = config.admin_username,
        admin_password = admin_password,
        license_server_url = license_server_url,
        license_api_key = license_api_key,
        license_grace_period = license_grace_period,
        license_public_key = license_public_key,
        port = config.http_port,
        app_host = app_host,
    );

    let env_path = install_dir.join(".env");
    std::fs::write(&env_path, &env_content)?;
    logs.push(LogEntry::success(format!(
        "Generated {}",
        env_path.display()
    )));

    // Set restrictive permissions on .env
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o600);
        std::fs::set_permissions(&env_path, perms)?;
        logs.push(LogEntry::info("Set .env permissions to 600"));
    }

    Ok(logs)
}

/// Detect the machine's primary non-loopback IP via `hostname -I`.
fn detect_local_ip() -> String {
    if let Ok(output) = super::run_command("hostname", &["-I"]) {
        let stdout = String::from_utf8_lossy(&output.stdout);
        if let Some(ip) = stdout.split_whitespace().next() {
            if !ip.is_empty() {
                return ip.to_string();
            }
        }
    }
    "localhost".to_string()
}

fn generate_random_string(length: usize) -> String {
    use rand::Rng;
    let chars: Vec<char> = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        .chars()
        .collect();
    let mut rng = rand::thread_rng();
    (0..length)
        .map(|_| chars[rng.gen_range(0..chars.len())])
        .collect()
}
