use anyhow::Result;

use crate::app::{InstallConfig, LogEntry};

pub fn generate_config(config: &InstallConfig) -> Result<Vec<LogEntry>> {
    let mut logs = Vec::new();

    let install_dir = &config.install_dir;

    // Generate passwords/keys if empty
    let db_password = if config.db_password.is_empty() {
        generate_random_string(24)
    } else {
        config.db_password.clone()
    };

    let admin_password = if config.admin_password.is_empty() {
        let pass = generate_random_string(16);
        logs.push(LogEntry::info(format!(
            "Generated admin password: {} (save this!)",
            pass
        )));
        pass
    } else {
        config.admin_password.clone()
    };

    let encryption_key = if config.connector_encryption_key.is_empty() {
        generate_random_string(32)
    } else {
        config.connector_encryption_key.clone()
    };

    // Build DATABASE_URL
    let database_url = format!(
        "postgresql://{}:{}@{}:{}/{}",
        config.db_user, db_password, config.db_host, config.db_port, config.db_name
    );

    // Generate .env file
    let env_content = format!(
        r#"# InfraWatch Configuration
# Generated by infrawatch-installer

# Database
DATABASE_URL={database_url}

# Security
CONNECTOR_ENCRYPTION_KEY={encryption_key}

# Admin User
ADMIN_USERNAME={admin_username}
ADMIN_PASSWORD={admin_password}

# License
LICENSE_SERVER_URL={license_url}
LICENSE_API_KEY=pk_live_RiTXxEttxQWgH3usHAVZjAMD0JBJb2P5KxS81qUk
LICENSE_GRACE_PERIOD_DAYS=7
LICENSE_PUBLIC_KEY=

# Server
PORT={port}
"#,
        database_url = database_url,
        encryption_key = encryption_key,
        admin_username = config.admin_username,
        admin_password = admin_password,
        license_url = config.license_server_url,
        port = config.http_port,
    );

    let env_path = install_dir.join(".env");
    std::fs::write(&env_path, &env_content)?;
    logs.push(LogEntry::success(format!(
        "Generated {}",
        env_path.display()
    )));

    // Set restrictive permissions on .env
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o600);
        std::fs::set_permissions(&env_path, perms)?;
        logs.push(LogEntry::info("Set .env permissions to 600"));
    }

    Ok(logs)
}

fn generate_random_string(length: usize) -> String {
    use rand::Rng;
    let chars: Vec<char> = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        .chars()
        .collect();
    let mut rng = rand::thread_rng();
    (0..length)
        .map(|_| chars[rng.gen_range(0..chars.len())])
        .collect()
}
